# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.24.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.24.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/chuck/Desktop/Epitech/B-CPP-500-MAR-5-1-rtype-gabriel.de-taxis-du-poet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/chuck/Desktop/Epitech/B-CPP-500-MAR-5-1-rtype-gabriel.de-taxis-du-poet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/Cellar/cmake/3.24.2/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/Cellar/cmake/3.24.2/bin/cpack --config ./CPackSourceConfig.cmake /Users/chuck/Desktop/Epitech/B-CPP-500-MAR-5-1-rtype-gabriel.de-taxis-du-poet/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.24.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"bin\" \"devel\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/chuck/Desktop/Epitech/B-CPP-500-MAR-5-1-rtype-gabriel.de-taxis-du-poet/CMakeFiles /Users/chuck/Desktop/Epitech/B-CPP-500-MAR-5-1-rtype-gabriel.de-taxis-du-poet//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/chuck/Desktop/Epitech/B-CPP-500-MAR-5-1-rtype-gabriel.de-taxis-du-poet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named R-Type-client

# Build rule for target.
R-Type-client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 R-Type-client
.PHONY : R-Type-client

# fast build rule for target.
R-Type-client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/build
.PHONY : R-Type-client/fast

#=============================================================================
# Target rules for targets named R-Type-server

# Build rule for target.
R-Type-server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 R-Type-server
.PHONY : R-Type-server

# fast build rule for target.
R-Type-server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-server.dir/build.make CMakeFiles/R-Type-server.dir/build
.PHONY : R-Type-server/fast

#=============================================================================
# Target rules for targets named sfml-system

# Build rule for target.
sfml-system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-system
.PHONY : sfml-system

# fast build rule for target.
sfml-system/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/System/CMakeFiles/sfml-system.dir/build.make _deps/sfml-build/src/SFML/System/CMakeFiles/sfml-system.dir/build
.PHONY : sfml-system/fast

#=============================================================================
# Target rules for targets named sfml-window

# Build rule for target.
sfml-window: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-window
.PHONY : sfml-window

# fast build rule for target.
sfml-window/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Window/CMakeFiles/sfml-window.dir/build.make _deps/sfml-build/src/SFML/Window/CMakeFiles/sfml-window.dir/build
.PHONY : sfml-window/fast

#=============================================================================
# Target rules for targets named sfml-network

# Build rule for target.
sfml-network: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-network
.PHONY : sfml-network

# fast build rule for target.
sfml-network/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Network/CMakeFiles/sfml-network.dir/build.make _deps/sfml-build/src/SFML/Network/CMakeFiles/sfml-network.dir/build
.PHONY : sfml-network/fast

#=============================================================================
# Target rules for targets named sfml-graphics

# Build rule for target.
sfml-graphics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-graphics
.PHONY : sfml-graphics

# fast build rule for target.
sfml-graphics/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/build.make _deps/sfml-build/src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/build
.PHONY : sfml-graphics/fast

#=============================================================================
# Target rules for targets named sfml-audio

# Build rule for target.
sfml-audio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-audio
.PHONY : sfml-audio

# fast build rule for target.
sfml-audio/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Audio/CMakeFiles/sfml-audio.dir/build.make _deps/sfml-build/src/SFML/Audio/CMakeFiles/sfml-audio.dir/build
.PHONY : sfml-audio/fast

#=============================================================================
# Target rules for targets named asio

# Build rule for target.
asio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 asio
.PHONY : asio

# fast build rule for target.
asio/fast:
	$(MAKE) $(MAKESILENT) -f _deps/asiocmake-build/CMakeFiles/asio.dir/build.make _deps/asiocmake-build/CMakeFiles/asio.dir/build
.PHONY : asio/fast

Client/Src/Assets.o: Client/Src/Assets.cpp.o
.PHONY : Client/Src/Assets.o

# target to build an object file
Client/Src/Assets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Assets.cpp.o
.PHONY : Client/Src/Assets.cpp.o

Client/Src/Assets.i: Client/Src/Assets.cpp.i
.PHONY : Client/Src/Assets.i

# target to preprocess a source file
Client/Src/Assets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Assets.cpp.i
.PHONY : Client/Src/Assets.cpp.i

Client/Src/Assets.s: Client/Src/Assets.cpp.s
.PHONY : Client/Src/Assets.s

# target to generate assembly for a file
Client/Src/Assets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Assets.cpp.s
.PHONY : Client/Src/Assets.cpp.s

Client/Src/Button.o: Client/Src/Button.cpp.o
.PHONY : Client/Src/Button.o

# target to build an object file
Client/Src/Button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Button.cpp.o
.PHONY : Client/Src/Button.cpp.o

Client/Src/Button.i: Client/Src/Button.cpp.i
.PHONY : Client/Src/Button.i

# target to preprocess a source file
Client/Src/Button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Button.cpp.i
.PHONY : Client/Src/Button.cpp.i

Client/Src/Button.s: Client/Src/Button.cpp.s
.PHONY : Client/Src/Button.s

# target to generate assembly for a file
Client/Src/Button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Button.cpp.s
.PHONY : Client/Src/Button.cpp.s

Client/Src/Game.o: Client/Src/Game.cpp.o
.PHONY : Client/Src/Game.o

# target to build an object file
Client/Src/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Game.cpp.o
.PHONY : Client/Src/Game.cpp.o

Client/Src/Game.i: Client/Src/Game.cpp.i
.PHONY : Client/Src/Game.i

# target to preprocess a source file
Client/Src/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Game.cpp.i
.PHONY : Client/Src/Game.cpp.i

Client/Src/Game.s: Client/Src/Game.cpp.s
.PHONY : Client/Src/Game.s

# target to generate assembly for a file
Client/Src/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Game.cpp.s
.PHONY : Client/Src/Game.cpp.s

Client/Src/Graphics.o: Client/Src/Graphics.cpp.o
.PHONY : Client/Src/Graphics.o

# target to build an object file
Client/Src/Graphics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Graphics.cpp.o
.PHONY : Client/Src/Graphics.cpp.o

Client/Src/Graphics.i: Client/Src/Graphics.cpp.i
.PHONY : Client/Src/Graphics.i

# target to preprocess a source file
Client/Src/Graphics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Graphics.cpp.i
.PHONY : Client/Src/Graphics.cpp.i

Client/Src/Graphics.s: Client/Src/Graphics.cpp.s
.PHONY : Client/Src/Graphics.s

# target to generate assembly for a file
Client/Src/Graphics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Graphics.cpp.s
.PHONY : Client/Src/Graphics.cpp.s

Client/Src/Menu.o: Client/Src/Menu.cpp.o
.PHONY : Client/Src/Menu.o

# target to build an object file
Client/Src/Menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Menu.cpp.o
.PHONY : Client/Src/Menu.cpp.o

Client/Src/Menu.i: Client/Src/Menu.cpp.i
.PHONY : Client/Src/Menu.i

# target to preprocess a source file
Client/Src/Menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Menu.cpp.i
.PHONY : Client/Src/Menu.cpp.i

Client/Src/Menu.s: Client/Src/Menu.cpp.s
.PHONY : Client/Src/Menu.s

# target to generate assembly for a file
Client/Src/Menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Menu.cpp.s
.PHONY : Client/Src/Menu.cpp.s

Client/Src/Systems/BulletControlSystem.o: Client/Src/Systems/BulletControlSystem.cpp.o
.PHONY : Client/Src/Systems/BulletControlSystem.o

# target to build an object file
Client/Src/Systems/BulletControlSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Systems/BulletControlSystem.cpp.o
.PHONY : Client/Src/Systems/BulletControlSystem.cpp.o

Client/Src/Systems/BulletControlSystem.i: Client/Src/Systems/BulletControlSystem.cpp.i
.PHONY : Client/Src/Systems/BulletControlSystem.i

# target to preprocess a source file
Client/Src/Systems/BulletControlSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Systems/BulletControlSystem.cpp.i
.PHONY : Client/Src/Systems/BulletControlSystem.cpp.i

Client/Src/Systems/BulletControlSystem.s: Client/Src/Systems/BulletControlSystem.cpp.s
.PHONY : Client/Src/Systems/BulletControlSystem.s

# target to generate assembly for a file
Client/Src/Systems/BulletControlSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Systems/BulletControlSystem.cpp.s
.PHONY : Client/Src/Systems/BulletControlSystem.cpp.s

Client/Src/Systems/MonsterControlSystem.o: Client/Src/Systems/MonsterControlSystem.cpp.o
.PHONY : Client/Src/Systems/MonsterControlSystem.o

# target to build an object file
Client/Src/Systems/MonsterControlSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Systems/MonsterControlSystem.cpp.o
.PHONY : Client/Src/Systems/MonsterControlSystem.cpp.o

Client/Src/Systems/MonsterControlSystem.i: Client/Src/Systems/MonsterControlSystem.cpp.i
.PHONY : Client/Src/Systems/MonsterControlSystem.i

# target to preprocess a source file
Client/Src/Systems/MonsterControlSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Systems/MonsterControlSystem.cpp.i
.PHONY : Client/Src/Systems/MonsterControlSystem.cpp.i

Client/Src/Systems/MonsterControlSystem.s: Client/Src/Systems/MonsterControlSystem.cpp.s
.PHONY : Client/Src/Systems/MonsterControlSystem.s

# target to generate assembly for a file
Client/Src/Systems/MonsterControlSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Systems/MonsterControlSystem.cpp.s
.PHONY : Client/Src/Systems/MonsterControlSystem.cpp.s

Client/Src/Systems/PlayerControlSystem.o: Client/Src/Systems/PlayerControlSystem.cpp.o
.PHONY : Client/Src/Systems/PlayerControlSystem.o

# target to build an object file
Client/Src/Systems/PlayerControlSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Systems/PlayerControlSystem.cpp.o
.PHONY : Client/Src/Systems/PlayerControlSystem.cpp.o

Client/Src/Systems/PlayerControlSystem.i: Client/Src/Systems/PlayerControlSystem.cpp.i
.PHONY : Client/Src/Systems/PlayerControlSystem.i

# target to preprocess a source file
Client/Src/Systems/PlayerControlSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Systems/PlayerControlSystem.cpp.i
.PHONY : Client/Src/Systems/PlayerControlSystem.cpp.i

Client/Src/Systems/PlayerControlSystem.s: Client/Src/Systems/PlayerControlSystem.cpp.s
.PHONY : Client/Src/Systems/PlayerControlSystem.s

# target to generate assembly for a file
Client/Src/Systems/PlayerControlSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/Systems/PlayerControlSystem.cpp.s
.PHONY : Client/Src/Systems/PlayerControlSystem.cpp.s

Client/Src/WindowManaging.o: Client/Src/WindowManaging.cpp.o
.PHONY : Client/Src/WindowManaging.o

# target to build an object file
Client/Src/WindowManaging.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/WindowManaging.cpp.o
.PHONY : Client/Src/WindowManaging.cpp.o

Client/Src/WindowManaging.i: Client/Src/WindowManaging.cpp.i
.PHONY : Client/Src/WindowManaging.i

# target to preprocess a source file
Client/Src/WindowManaging.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/WindowManaging.cpp.i
.PHONY : Client/Src/WindowManaging.cpp.i

Client/Src/WindowManaging.s: Client/Src/WindowManaging.cpp.s
.PHONY : Client/Src/WindowManaging.s

# target to generate assembly for a file
Client/Src/WindowManaging.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/WindowManaging.cpp.s
.PHONY : Client/Src/WindowManaging.cpp.s

Client/Src/main.o: Client/Src/main.cpp.o
.PHONY : Client/Src/main.o

# target to build an object file
Client/Src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/main.cpp.o
.PHONY : Client/Src/main.cpp.o

Client/Src/main.i: Client/Src/main.cpp.i
.PHONY : Client/Src/main.i

# target to preprocess a source file
Client/Src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/main.cpp.i
.PHONY : Client/Src/main.cpp.i

Client/Src/main.s: Client/Src/main.cpp.s
.PHONY : Client/Src/main.s

# target to generate assembly for a file
Client/Src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-client.dir/build.make CMakeFiles/R-Type-client.dir/Client/Src/main.cpp.s
.PHONY : Client/Src/main.cpp.s

Server/main.o: Server/main.cpp.o
.PHONY : Server/main.o

# target to build an object file
Server/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-server.dir/build.make CMakeFiles/R-Type-server.dir/Server/main.cpp.o
.PHONY : Server/main.cpp.o

Server/main.i: Server/main.cpp.i
.PHONY : Server/main.i

# target to preprocess a source file
Server/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-server.dir/build.make CMakeFiles/R-Type-server.dir/Server/main.cpp.i
.PHONY : Server/main.cpp.i

Server/main.s: Server/main.cpp.s
.PHONY : Server/main.s

# target to generate assembly for a file
Server/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/R-Type-server.dir/build.make CMakeFiles/R-Type-server.dir/Server/main.cpp.s
.PHONY : Server/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... R-Type-client"
	@echo "... R-Type-server"
	@echo "... asio"
	@echo "... sfml-audio"
	@echo "... sfml-graphics"
	@echo "... sfml-network"
	@echo "... sfml-system"
	@echo "... sfml-window"
	@echo "... Client/Src/Assets.o"
	@echo "... Client/Src/Assets.i"
	@echo "... Client/Src/Assets.s"
	@echo "... Client/Src/Button.o"
	@echo "... Client/Src/Button.i"
	@echo "... Client/Src/Button.s"
	@echo "... Client/Src/Game.o"
	@echo "... Client/Src/Game.i"
	@echo "... Client/Src/Game.s"
	@echo "... Client/Src/Graphics.o"
	@echo "... Client/Src/Graphics.i"
	@echo "... Client/Src/Graphics.s"
	@echo "... Client/Src/Menu.o"
	@echo "... Client/Src/Menu.i"
	@echo "... Client/Src/Menu.s"
	@echo "... Client/Src/Systems/BulletControlSystem.o"
	@echo "... Client/Src/Systems/BulletControlSystem.i"
	@echo "... Client/Src/Systems/BulletControlSystem.s"
	@echo "... Client/Src/Systems/MonsterControlSystem.o"
	@echo "... Client/Src/Systems/MonsterControlSystem.i"
	@echo "... Client/Src/Systems/MonsterControlSystem.s"
	@echo "... Client/Src/Systems/PlayerControlSystem.o"
	@echo "... Client/Src/Systems/PlayerControlSystem.i"
	@echo "... Client/Src/Systems/PlayerControlSystem.s"
	@echo "... Client/Src/WindowManaging.o"
	@echo "... Client/Src/WindowManaging.i"
	@echo "... Client/Src/WindowManaging.s"
	@echo "... Client/Src/main.o"
	@echo "... Client/Src/main.i"
	@echo "... Client/Src/main.s"
	@echo "... Server/main.o"
	@echo "... Server/main.i"
	@echo "... Server/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

